### ISSUE TITLE
Creating a new (second) window with player throws AccessViolationException

### ISSUE THREAD

**Issue by DominikPalo** [ZeBobo5/Vlc.DotNet#22]
When I try to open a new WPF window with VlcControl after first window with VlcControl was closed, this exception is thrown:

```
System.AccessViolationException was unhandled
  _HResult=-2147467261
  _message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
  HResult=-2147467261
  IsTransient=false
  Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
  Source=Vlc.DotNet.Core.Interops
  StackTrace:
       at Vlc.DotNet.Core.Interops.VlcManager.ReleaseMediaPlayer(VlcMediaPlayerInstance mediaPlayerInstance)
       at Vlc.DotNet.Core.Interops.VlcMediaPlayerInstance.Dispose(Boolean disposing)
       at Vlc.DotNet.Core.Interops.Signatures.InteropObjectInstance.Dispose()
       at Vlc.DotNet.Core.VlcMediaPlayer.Dispose(Boolean disposing)
       at Vlc.DotNet.Core.VlcMediaPlayer.Dispose()
       at Vlc.DotNet.Forms.VlcControl.Dispose(Boolean disposing)
       at System.ComponentModel.Component.Dispose()
       at Vlc.DotNet.Wpf.VlcControl.DestroyWindowCore(HandleRef hwnd)
       at System.Windows.Interop.HwndHost.DestroyWindow()
       at System.Windows.Interop.HwndHost.AsyncDestroyWindow(Object arg)
       at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
       at System.Windows.Threading.DispatcherOperation.InvokeImpl()
       at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Windows.Threading.DispatcherOperation.Invoke()
       at System.Windows.Threading.Dispatcher.ProcessQueue()
       at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
       at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
       at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
       at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
       at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
       at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
       at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
       at System.Windows.Threading.Dispatcher.Run()
       at System.Windows.Application.RunDispatcher(Object ignore)
       at System.Windows.Application.RunInternal(Window window)
       at System.Windows.Application.Run(Window window)
       at System.Windows.Application.Run()
       at SlidesDrive.App.Main() in c:\Users\Dominik\Projects\slidessync\SlidesSync\SlidesSync\obj\x86\Debug\App.g.cs:line 0
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.Runtime.Hosting.ManifestRunner.Run(Boolean checkAptModel)
       at System.Runtime.Hosting.ManifestRunner.ExecuteAsAssembly()
       at System.Runtime.Hosting.ApplicationActivator.CreateInstance(ActivationContext activationContext, String[] activationCustomData)
       at System.Runtime.Hosting.ApplicationActivator.CreateInstance(ActivationContext activationContext)
       at System.Activator.CreateInstance(ActivationContext activationContext)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssemblyDebugInZone()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 
```

**Comment by sepehr1014** [comment]
I faced the same exception. It originates from void ReleaseMediaPlayer(VlcMediaPlayerInstance mediaPlayerInstance) in VlcManager.ReleaseMediaPlayer.cs from Vlc.DotNet.Core.Interops

**Comment by DominikPalo** [comment]
I found a workaround: If you set position of old video to end position before closing first window
    myVlcControl.MediaPlayer.Position = 1f;
instead of calling Stop
    myVlcControl.MediaPlayer.Stop();
exception was not thrown and video in new window works fine.

**Comment by sepehr1014** [comment]
Thanks Dominik, but I only have one window and when it's closed, I get that exception.
I tried your code at Window.Closing event, but I still get that exception. Any idea?

**Comment by jeboi** [comment]
It's kind of a hack, but you can mark the method that throws the AccessViolationException with `[HandleProcessCorruptedStateExceptions]`, this allows you to catch exception. See: http://stackoverflow.com/a/4759831

**Comment by TobiasOskarsson** [comment]
Isn't it dangerous to just catch the exception? Thinking about leaving stuff in the memory. A better solution should be possible, I also noticed that this only happens when you're running "Release" or "Debug" and you're closing the WPF window BEFORE the debugging/vlc window.

**Comment by bbougot** [comment]
Same thing here. It is unusable and really prompt to memory leak. We should fix this annoying bug.

**Comment by jeboi** [comment]
It is definitely not the best solution, the AccessViolationException also occurs on deployed versions. I am now running multiple (5+) windows with a stream. I removed the line that calls `vlcControl.MediaPlayer.Dispose();` and the exception does not occur. 

However, when closing the windows, the last window will throw the exception on the `Application_Exit` event that I can't catch using the `[HandleProcessCorruptedStateExceptions]` tag. Somehow the garbage collector can't dispose the object because it was never instantiated. 

A dirty fix to this is terminate the process, thus freeing the corrupted memory.

**Comment by webdreamerkid** [comment]
I'm seeing the same issue. Is this issue fixed by "Fixes #14 - Application using Vlc.Net crashes on exit"?
https://github.com/ZeBobo5/Vlc.DotNet/commit/c3a4ed9b4de2cf3ed011643cd92c15244c0d399a

**Comment by Victor-Hugo** [comment]
This is my VB.NET Solution for Vlc.DotNet.Forms

Dim VLC_Control As Vlc.DotNet.Forms.VlcControl
'------ VLC_Control instancing in other procedure
'------ VLC_Control playing in other procedure
'------ Other code..
'---- Finally:
Sub EndWindowOrProgram()
VLC_Control.Position = 31 '1f Hex
Me.Controls.Remove(VLC_Control) 'Remove VLC control from current Form 
GC.SuppressFinalize(VLC_Control) 'Force to dispose the object with garbage collector
VLC_Control= Nothing
End
End Sub

**Comment by Secheron** [comment]
I need to use up to 25 instance of VlcControl on the same window in a WPF application.
Problem:
Call VlcControl.MediaPlayer.Dispose work fine with a single instance at the same time.
If I have more than 1 instance am running and I want to dispose them (or not), the application crash on exit (Same messages as other posts).

I use the nuget library version 2.1.62.0.
I don't want to use [HandleProcessCorruptedStateExceptions]

Fixed issue in lib but not in nuget dll's?

Example:
![code](https://cloud.githubusercontent.com/assets/11715521/10544802/c1d36ce6-7425-11e5-9a9f-2d123d38fd4a.png)

**Comment by wolf-germany** [comment]
@Secheron The nuget dll's are "very old", I think the version is build in March. On my side the application do not crash on close, while using the source code from here.

**Comment by Secheron** [comment]
@wolf-germany Thanks a lot for your reply. I have now compiled dll's from here. I don't have AcessViolation, so this problem is effectively solved.

**Comment by SkinnySackboy** [comment]
Is there any plan to publish the latest to NuGet.org? Would the owner be able to do this please?

**Comment by ZeBobo5** [comment]
I just added an auto nuget publishing :)

**Comment by msddevelopment** [comment]
I have the same problem as Secheron commented on 16 Oct 2015. If many VlcControl instances are used in the same software, does each VlcControl.MediaPlayer need his own instance of DirectoryInfo?

I am working with the latest release (commit 11834fa on 3 Feb 2017).

Thanks for any suggestions!

**Comment by xpachin** [comment]
hey Secheron, how did  you managed to have 25 instances at the same time? when i got 6 the programm crashes with the memory acces violaation

**Comment by Secheron** [comment]
Hi Xpachin,

It's hard to give you an answer without further details:

1) With 5 instances, your programm work fine?
2) Are you using the latest version?
3) Do you stop the player before play another source?
4) If you work with a collection of vlc controls, do you assign new vlc control to the collection while your program is running (it was a problem at the time when I used it in october 2015)?
