### ISSUE TITLE
Issues while saving recording ( Event manager is not initialized)

### ISSUE THREAD

**Issue by Jawadahmed2015** [ZeBobo5/Vlc.DotNet#511]
I am facing some issues while recording streaming using Vlc.DotNet. libs 

# Generic information

- **Vlc.DotNet version** : (2.2.1 )
- **Vlc.DotNet project used** : (WinForms)
- **libvlc version** : (Please fill) (x86/x64) + how did you get it?
- **.net version** : (Please fill)
- **Project language** : (C#)
- **Project build architecture** : (x86)
- **Operating system** : (Windows x64) 
# Summary

I am saving live streaming in a folder, I have set the time by my self e.g 1 minute so after every 1 minute it will save the live streaming video . I am using following code to achieve this task.

 var stopTime = Convert.ToInt16(txt_ContiunesRecordingMints.Text.Trim()) * 60000;
            var aTimer = new System.Timers.Timer(stopTime);
            // Hook up the Elapsed event for the timer. 
            aTimer.Elapsed += OnTimedEvent;
            aTimer.AutoReset = true;

 System.Threading.ThreadPool.QueueUserWorkItem((a) =>
                {
                    string final = System.DateTime.Now.ToString("yyyy_MM_dd_HH_mm_ss") + ".mp4";
                    var mediaOptions = new string[]
                   {
                   ":network-caching=0",
                    ":sout=#duplicate{dst=std{access=file,mux=" + "mp4" + ",dst='" +currentPath + "\\"+ final + "'},dst=display}",
                    };

                    vlcControl1.Play("rtsp://192.168.2.221:554/Onvif/live/1/1", mediaOptions);
                    aTimer.Enabled = true; // o
                });

above code is able to save file but after 4-5 iterations exception occur at this line

 vlcControl1.Play("rtsp://192.168.2.221:554/Onvif/live/1/1", mediaOptions); 

kindly see the attached image for details

![mainissue1](https://user-images.githubusercontent.com/11055598/51467291-a81f7300-1d85-11e9-8008-95c0cf14dca5.png)

![issue1](https://user-images.githubusercontent.com/11055598/51465858-385bb900-1d82-11e9-81cb-4a18702520c9.png)

 Someone can please tell me what i am doing wrong?

**Comment by jeremyVignelles** [comment]
Could you try with the 3.0 prerelease?

**Comment by Jawadahmed2015** [comment]
@jeremyVignelles  thanks for your quick response

Yes I have updated my libraries to 3.0.0-develop328 now after 2 iterations i got a new expection

An unhandled exception of type 'System.AccessViolationException' occurred in Vlc.DotNet.Core.Interops.dll
Attempted to read or write protected memory. This is often an indication that other memory is corrupt.


Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Vlc.DotNet.Core.Interops.VlcManager.ReleaseMedia(VlcMediaInstance mediaInstance)
   at Vlc.DotNet.Core.Interops.VlcMediaInstance.Dispose(Boolean disposing)
   at Vlc.DotNet.Core.Interops.Signatures.InteropObjectInstance.Finalize()
The program '[21708] WindowsFormsApplication1.exe' has exited with code 0 (0x0).

**Comment by Jawadahmed2015** [comment]
@jeremyVignelles 

Exception is changed without changing any line of code I have added try catch code place a debugger on the catch block still it wont hit on catch block, it simply close the application. following are some lines i copied from output tab  


[067dafb0] main libvlc debug: VLC media player - 3.0.4 Vetinari
[067dafb0] main libvlc debug: Copyright Â© 1996-2018 the VideoLAN team
[067dafb0] main libvlc debug: revision 3.0.4-0-gf615db6332
[067dafb0] main libvlc debug: configured with ../extras/package/win32/../../../configure  '--enable-update-check' '--enable-lua' '--enable-faad' '--enable-flac' '--enable-theora' '--enable-avcodec' '--enable-merge-ffmpeg' '--enable-dca' '--enable-mpc' '--enable-libass' '--enable-schroedinger' '--enable-realrtsp' '--enable-live555' '--enable-dvdread' '--enable-shout' '--enable-goom' '--enable-caca' '--enable-qt' '--enable-skins2' '--enable-sse' '--enable-mmx' '--enable-libcddb' '--enable-zvbi' '--disable-telx' '--enable-nls' '--host=i686-w64-mingw32' '--with-breakpad=https://win.crashes.videolan.org' 'host_alias=i686-w64-mingw32' 'PKG_CONFIG_LIBDIR=/home/jenkins/workspace/vlc-release/windows/vlc-release-win32-x86/contrib/i686-w64-mingw32/lib/pkgconfig'
[067dafb0] main libvlc debug: using multimedia timers as clock source
[067dafb0] main libvlc debug:  min period: 1 ms, max period: 1000000 ms
[067dafb0] main libvlc debug: searching plug-in modules
[067dafb0] main libvlc debug: loading plugins cache file C:\Program Files (x86)\VideoLAN\VLC\plugins\plugins.dat
[067dafb0] main libvlc debug: recursively browsing `C:\Program Files (x86)\VideoLAN\VLC\plugins'
[067dafb0] main libvlc debug: plug-ins loaded: 490 modules
[067db158] main logger debug: looking for logger module matching "any": 2 candidates
[067db158] main logger debug: using logger module "console"
[067dafb0] main libvlc debug: translation test: code is "C"
[06885be0] main keystore debug: looking for keystore module matching "memory": 3 candidates
[06885be0] main keystore debug: using keystore module "memory"
[067dafb0] main libvlc debug: CPU has capabilities MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4.1 SSE4.2 FPU 
[068aedd0] main generic debug: creating audio output
[068855e8] main audio output debug: looking for audio output module matching "any": 6 candidates
[068855e8] mmdevice audio output error: cannot initialize COM (error 0x80010106)
[068855e8] directsound audio output debug: found 3 devices
[068855e8] main audio output debug: using audio output module "directsound"
[068aedd0] main generic debug: keeping audio output
[068aeee8] main generic debug: creating audio output
[06888e90] main audio output debug: looking for audio output module matching "any": 6 candidates
[06888e90] mmdevice audio output error: cannot initialize COM (error 0x80010106)
[06888e90] directsound audio output debug: found 3 devices
[06888e90] main audio output debug: using audio output module "directsound"
[068aeee8] main generic debug: keeping audio output
[06888e90] main audio output debug: removing module "directsound"
The program '[12032] WindowsFormsApplication1.exe' has exited with code 3 (0x3).

**Comment by jeremyVignelles** [comment]
Please send the full code so I can help you, for example on a github repository.

**Comment by Jawadahmed2015** [comment]
@jeremyVignelles  as per your requirement here is my gihub repository link

https://github.com/Jawadahmed2015/VLC

just put 1 in the textbox and click on record after saving 4-5 files visual studio will be automatically closed the application, if you click on output you will see this message
**visual studio has exited with code 3 (0x3)**

I am using VS2017

**Comment by Jawadahmed2015** [comment]
@jeremyVignelles  any update on this issue? I really want to this feature in my project can you please give me any estimated time.

Thanks.

**Comment by jeremyVignelles** [comment]
`aTimer.AutoReset = true;` is wrong: You create a timer, start it, and when it triggers, it automatically restarts. You create a second timer at that time, with the same characteristics.
After 4 loops, you are calling Play() 4 times simultaneously, which, I suppose, causes VLC to fail with a race condition.

Try with `var stopTime = 10000;` to make it fail faster...

**Comment by jeremyVignelles** [comment]
By the way, `":network-caching=0",` will probably be too low for VLC 3, and starting a new VLC each time will create gaps between files...

**Comment by Jawadahmed2015** [comment]
@jeremyVignelles  By the way, ":network-caching=0", will probably be too low for VLC 3, and starting a new VLC each time will create gaps between files... then whats the workaround for this, because I have to create files after every 10-15 mints?

**Comment by Jawadahmed2015** [comment]
@jeremyVignelles I have removed the aTimer.AutoReset = true; also remove ":network-caching=0" still after 4 loops program exit with following expection
The program '[8624] VLCRecording.exe' has exited with code -1073610751 (0xc0020001). 

Can you please guide me now whats the main issue?

**Comment by jeremyVignelles** [comment]
With VLC itself, it's quite hard to do. Please see a similar issue here : #504

For your crash, it's hard to say for sure, do you have logs?
