### ISSUE TITLE
It takes to long to stop VlcMediaPlayer

### ISSUE THREAD

**Issue by milkyway007** [ZeBobo5/Vlc.DotNet#582]
I have an issue / a question (pick one) about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : 3.0.1
- **Vlc.DotNet project used** : Core
- **libvlc version** : 3.0.7.1 x86
- **.net version** : 4.5
- **Project language** : C#
- **Project build architecture** : AnyCPU
- **Operating system** : Windows x64

# Summary

I have a simple WPF application. The application records an RTSP stream to a file. For this purpose Vlc.DotNet library is used.

I have tested the application with two computers and the results are the same for both.

The application code is given below.

```
    public partial class MainWindow : Window
    {
        private IPath _pathWrapper;
        private IDirectoryInfo _vlcLibDirectory;
        private VlcMediaPlayer _videoRecorder;

        public MainWindow()
        {
            InitializeComponent();
        }

        private void OnButtonClick(object sender, RoutedEventArgs e)
        {
            if (_videoRecorder != null && _videoRecorder.IsPlaying())
            {
                _videoRecorder.Stop();
                Button.Background = Brushes.Blue;
                _videoRecorder = null;
                return;
            }

            string currentDirectory = AppDomain.CurrentDomain.BaseDirectory;
            _pathWrapper = new PathWrap();
            _vlcLibDirectory = new DirectoryInfoWrap(_pathWrapper.Combine(currentDirectory, "libvlc", IntPtr.Size == 4 ? "win-x86" : "win-x64"));
            var options = new string[]
            {
                "--file-logging",
                "--logfile=OnvifVideoRecording.log",
                "-vvv"
            };
            _videoRecorder = new VlcMediaPlayer(_vlcLibDirectory.DirectoryInfo, options);

            // TODO: Make sure the path combination does not already exist at the generator
            //string fileDestination = "\\\\\\BuildSrv\\Videos\\A, A, 1\\test.mp4";
            string fileDestination = @"D:\Media\Video\A, A, 1\test.mp4";

            if (File.Exists(fileDestination))
            {
                File.Delete(fileDestination);
            }

            // TODO: How to start VLC video recording without the WPF control? Use field with VLC 'player' instance.
            string[] mediaOptions =
            {
                ":sout=#file{dst='" + fileDestination + "'}",
                ":sout-keep"
            };

            _videoRecorder.SetMedia("rtsp://192.168.1.110:5504/channel=0,stream=0", mediaOptions);
            _videoRecorder.Play();
            Button.Background = Brushes.Red;
        }
    }

```
The application has a window. The window has a button. When this button is pressed for the first time, recording a video file is started and the button turns red. I usually record video files for 10 minutes. When the button is pressed for the second time, recording a video file is stopped and the button turns blue.

If I record a file to the local destination (to the same computer where the program is run, for example, D:\Media\Video\A, A, 1\test.mp4), everything is ok. Recording video file is started and stopped quickly, almost immediately.

The problems occur when I try to record a file to the remote computer (for example, \\BuildSrv\Videos\A, A, 1\test.mp4). Recording a video file starts immediately. However, _videoRecorder.Stop() takes approximately 30 seconds – 1 minute. Resource monitor shows very high network use (90% in case of one computer and 100% in case of another) after the button is pressed for the second time (recording video is stopped). The longer the recorded video file is, the more time is needed to stop VlcMediaPlayer.

Why does stopping VlcMediaPlayer takes so much time in case of recording an RTSP stream to the remote computer? Can this problem be solved somehow?

- [ ] I confirm that my issue doesn't happen in VLC itself.

**Comment by mfkl** [comment]
Maybe related https://code.videolan.org/videolan/LibVLCSharp/issues/214

**Comment by milkyway007** [comment]
So I can do nothing to verify this hypothesis if I do not know how to compile a recent nightly libvlc build?

**Comment by mfkl** [comment]
You could try a libvlc 4 build to see if that changes anything, but neither vlc.dotnet nor libvlcsharp supports it yet, because it's still unstable.

**Comment by milkyway007** [comment]
I downloaded vlc-4.0.0-20191004-0250-dev-win32.zip, unzipped it and pasted needed files to the bin folder. I get next exception:

System.MissingMethodException
  HResult=0x80131513
  Message=The address of the function 'libvlc_media_player_stop' does not exist in libvlc library.
  Source=Vlc.DotNet.Core.Interops
  StackTrace:
   at Vlc.DotNet.Core.Interops.VlcLibraryLoader.GetInteropDelegate[T]() in C:\Users\liidia\Documents\Vlc.DotNet-develop\Vlc.DotNet-develop\src\Vlc.DotNet.Core.Interops\VlcLibraryLoader.cs:line 98
   at Vlc.DotNet.Core.Interops.VlcManager.Stop(VlcMediaPlayerInstance mediaPlayerInstance) in C:\Users\liidia\Documents\Vlc.DotNet-develop\Vlc.DotNet-develop\src\Vlc.DotNet.Core.Interops\VlcManager.Stop.cs:line 12
   at Vlc.DotNet.Core.VlcMediaPlayer.Stop() in C:\Users\liidia\Documents\Vlc.DotNet-develop\Vlc.DotNet-develop\src\Vlc.DotNet.Core\VlcMediaPlayer\VlcMediaPlayer.cs:line 216
   at MyWpfApp.MainWindow.OnButtonClick(Object sender, RoutedEventArgs e) in C:\Users\liidia\Documents\Vlc.DotNet-develop\Vlc.DotNet-develop\src\MyWpfApp\MainWindow.xaml.cs:line 40
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at MyWpfApp.App.Main()

Inner Exception 1:
Win32Exception: The specified procedure could not be found

**Comment by mfkl** [comment]
You can contribute changes to vlc.dotnet so that a preview version of it supports libvlc 4. But libvlc 4 is not available on nuget yet, so it will be confusing for a lot of users. You can start by patching locally, by adding support for the async version of `stop` in vlc.dotnet.

**Comment by milkyway007** [comment]
I did as you said.
In VlcMediaPlayer I added method StopAsyn(...):
```
public void StopAsync()
        {
            Manager.StopAsync(myMediaPlayerInstance);
        }

```
In VlcManager I added method StopAsyn(...):
```
public void StopAsync(VlcMediaPlayerInstance mediaPlayerInstance)
        {
            if (mediaPlayerInstance == IntPtr.Zero)
                throw new ArgumentException("Media player instance is not initialized.");
            myLibraryLoader.GetInteropDelegate<StopAsync>().Invoke(mediaPlayerInstance);
        }
```
In the namespace Vlc.DotNet.Core.Interops.Signatures I added next code:
```
[LibVlcFunction("libvlc_media_player_stop_async")]
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal delegate void StopAsync(IntPtr mediaPlayerInstance);
```

Now stream recording to file stops immediately, but sometimes (in the most cases) resultant file is defective and it is impossible to open it.

**Comment by mfkl** [comment]
the nightly builds can be unstable so it could be anything. You have logs?

**Comment by milkyway007** [comment]
The log is here:

```
libVlc : Debug Copyright © 1996-2019 the VideoLAN team @ main
libVlc : Debug VLC media player - 4.0.0-dev Otto Chriek @ main
libVlc : Debug revision 4.0.0-dev-9500-gff11419a43 @ main
libVlc : Debug configured with ../extras/package/win32/../../../configure  '--enable-update-check' '--enable-lua' '--enable-faad' '--enable-flac' '--enable-theora' '--enable-avcodec' '--enable-merge-ffmpeg' '--enable-dca' '--enable-libass' '--enable-schroedinger' '--enable-live555' '--enable-dvdread' '--enable-shout' '--enable-goom' '--enable-caca' '--enable-qt' '--enable-skins2' '--enable-sse' '--enable-mmx' '--enable-libcddb' '--enable-zvbi' '--disable-telx' '--enable-nls' '--host=i686-w64-mingw32' '--enable-debug' 'host_alias=i686-w64-mingw32' 'PKG_CONFIG_LIBDIR=/home/jenkins/workspace/vlc-nightly/vlc-nightly-win32-x86/contrib/i686-w64-mingw32/lib/pkgconfig' @ main
libVlc : Debug Creating an input for 'rtsp://192.168.1.110:5504/channel=0,stream=0' @ main
libVlc : Debug using sout chain=`file{dst='\\\BuildSrv\Videos\A, A, 1\test.mp4'}' @ main
libVlc : Debug set config option: sout-standard-dst to \\BuildSrv\Videos\A, A, 1\test.mp4 @ main
libVlc : Debug stream=`file' @ main
libVlc : Debug looking for sout stream module matching "file": 24 candidates @ main
libVlc : Debug looking for sout access module matching "file": 11 candidates @ main
libVlc : Debug file access output opened (\\BuildSrv\Videos\A, A, 1\test.mp4) @ file
libVlc : Debug using sout access module "file" @ main
libVlc : Debug looking for sout mux module matching "mp4": 11 candidates @ main
libVlc : Debug Mp4 muxer opened @ mp4
libVlc : Debug using sout mux module "mp4" @ main
libVlc : Debug using `file/mp4://\\BuildSrv\Videos\A, A, 1\test.mp4' @ stream_out_standard
libVlc : Debug using sout stream module "stream_out_standard" @ main
libVlc : Debug using timeshift granularity of 50 MiB @ main
libVlc : Debug using timeshift path: C:\Users\liidia\AppData\Local\Temp @ main
libVlc : Debug `rtsp://192.168.1.110:5504/channel=0,stream=0' gives access `rtsp' demux `any' path `192.168.1.110:5504/channel=0,stream=0' @ main
libVlc : Debug creating access: rtsp://192.168.1.110:5504/channel=0,stream=0 @ main
libVlc : Debug  (path: \\192.168.1.110:5504\channel=0,stream=0) @ main
libVlc : Debug looking for access module matching "rtsp": 40 candidates @ main
libVlc : Debug version 2016.11.28 @ live555
libVlc : Debug RTP subsession 'video/H264' @ live555
libVlc : Debug selecting program id=0 @ main
libVlc : Debug Trying Lua scripts in C:\Users\liidia\Documents\Vlc.DotNet-develop\Vlc.DotNet-develop\src\MyWpfApp\bin\Debug\libvlc\win-x86\lua\playlist @ lua
libVlc : Debug setup start: 0.000000 stop:0.000000 @ live555
libVlc : Debug using access module "live555" @ main
libVlc : Debug We have a timeout of 60 seconds @ live555
libVlc : Debug play start: 0.000000 stop:0.000000 @ live555
libVlc : Debug looking for stream_filter module matching "any": 25 candidates @ main
libVlc : Debug not enough data @ playlist
libVlc : Debug Trying Lua scripts in C:\Users\liidia\AppData\Roaming\vlc\lua\playlist @ lua
libVlc : Debug Trying Lua playlist script C:\Users\liidia\Documents\Vlc.DotNet-develop\Vlc.DotNet-develop\src\MyWpfApp\bin\Debug\libvlc\win-x86\lua\playlist\soundcloud.luac @ lua
libVlc : Debug Trying Lua playlist script C:\Users\liidia\Documents\Vlc.DotNet-develop\Vlc.DotNet-develop\src\MyWpfApp\bin\Debug\libvlc\win-x86\lua\playlist\anevia_xml.luac @ lua
libVlc : Debug Trying Lua playlist script C:\Users\liidia\Documents\Vlc.DotNet-develop\Vlc.DotNet-develop\src\MyWpfApp\bin\Debug\libvlc\win-x86\lua\playlist\appletrailers.luac @ lua
libVlc : Debug Trying Lua playlist script C:\Users\liidia\Documents\Vlc.DotNet-develop\Vlc.DotNet-develop\src\MyWpfApp\bin\Debug\libvlc\win-x86\lua\playlist\twitch.luac @ lua
libVlc : Debug Trying Lua playlist script C:\Users\liidia\Documents\Vlc.DotNet-develop\Vlc.DotNet-develop\src\MyWpfApp\bin\Debug\libvlc\win-x86\lua\playlist\newgrounds.luac @ lua
libVlc : Debug Trying Lua playlist script C:\Users\liidia\Documents\Vlc.DotNet-develop\Vlc.DotNet-develop\src\MyWpfApp\bin\Debug\libvlc\win-x86\lua\playlist\koreus.luac @ lua
libVlc : Debug Trying Lua playlist script C:\Users\liidia\Documents\Vlc.DotNet-develop\Vlc.DotNet-develop\src\MyWpfApp\bin\Debug\libvlc\win-x86\lua\playlist\bbc_co_uk.luac @ lua
libVlc : Debug Trying Lua playlist script C:\Users\liidia\Documents\Vlc.DotNet-develop\Vlc.DotNet-develop\src\MyWpfApp\bin\Debug\libvlc\win-x86\lua\playlist\vimeo.luac @ lua
libVlc : Debug Trying Lua playlist script C:\Users\liidia\Documents\Vlc.DotNet-develop\Vlc.DotNet-develop\src\MyWpfApp\bin\Debug\libvlc\win-x86\lua\playlist\anevia_streams.luac @ lua
libVlc : Debug Trying Lua playlist script C:\Users\liidia\Documents\Vlc.DotNet-develop\Vlc.DotNet-develop\src\MyWpfApp\bin\Debug\libvlc\win-x86\lua\playlist\cue.luac @ lua
libVlc : Debug Trying Lua playlist script C:\Users\liidia\Documents\Vlc.DotNet-develop\Vlc.DotNet-develop\src\MyWpfApp\bin\Debug\libvlc\win-x86\lua\playlist\liveleak.luac @ lua
libVlc : Debug Trying Lua playlist script C:\Users\liidia\Documents\Vlc.DotNet-develop\Vlc.DotNet-develop\src\MyWpfApp\bin\Debug\libvlc\win-x86\lua\playlist\dailymotion.luac @ lua
libVlc : Debug Trying Lua playlist script C:\Users\liidia\Documents\Vlc.DotNet-develop\Vlc.DotNet-develop\src\MyWpfApp\bin\Debug\libvlc\win-x86\lua\playlist\vocaroo.luac @ lua
libVlc : Debug Trying Lua playlist script C:\Users\liidia\Documents\Vlc.DotNet-develop\Vlc.DotNet-develop\src\MyWpfApp\bin\Debug\libvlc\win-x86\lua\playlist\youtube.luac @ lua
libVlc : Debug Trying Lua playlist script C:\Users\liidia\Documents\Vlc.DotNet-develop\Vlc.DotNet-develop\src\MyWpfApp\bin\Debug\libvlc\win-x86\lua\playlist\rockbox_fm_presets.luac @ lua
libVlc : Debug Trying Lua playlist script C:\Users\liidia\Documents\Vlc.DotNet-develop\Vlc.DotNet-develop\src\MyWpfApp\bin\Debug\libvlc\win-x86\lua\playlist\jamendo.luac @ lua
libVlc : Debug found NAL_SPS (sps_id=0) @ h264
libVlc : Debug no stream_filter modules matched @ main
libVlc : Debug looking for packetizer module matching "any": 25 candidates @ main
libVlc : Debug found NAL_PPS (pps_id=0 sps_id=0) @ h264
libVlc : Debug using packetizer module "h264" @ main
libVlc : Debug starting in sync mode @ main
libVlc : Debug looking for meta reader module matching "any": 2 candidates @ main
libVlc : Debug Trying Lua scripts in C:\Users\liidia\AppData\Roaming\vlc\lua\meta\reader @ lua
libVlc : Debug Trying Lua scripts in C:\Users\liidia\Documents\Vlc.DotNet-develop\Vlc.DotNet-develop\src\MyWpfApp\bin\Debug\libvlc\win-x86\lua\meta\reader @ lua
libVlc : Debug Trying Lua playlist script C:\Users\liidia\Documents\Vlc.DotNet-develop\Vlc.DotNet-develop\src\MyWpfApp\bin\Debug\libvlc\win-x86\lua\meta\reader\filename.luac @ lua
libVlc : Debug no meta reader modules matched @ main
libVlc : Debug `rtsp://192.168.1.110:5504/channel=0,stream=0' successfully opened @ main
libVlc : Debug switching to async mode @ main
libVlc : Debug Buffering 0% @ main
libVlc : Debug lost 395906 bytes @ live555
libVlc : Debug Buffering 3% @ main
libVlc : Debug Buffering 1% @ main
libVlc : Debug increasing buffer size to 500000 @ live555
libVlc : Debug adding input @ mp4
libVlc : Debug adding a new sout input for `h264` (sout_input: 12C85F20) @ main
libVlc : Debug adding a new input @ main
libVlc : Debug Buffering 6% @ main
libVlc : Debug Buffering 31% @ main
libVlc : Debug Buffering 35% @ main
libVlc : Debug Buffering 39% @ main
libVlc : Debug Buffering 43% @ main
libVlc : Debug Buffering 47% @ main
libVlc : Debug Buffering 51% @ main
libVlc : Debug Buffering 55% @ main
libVlc : Debug Buffering 59% @ main
libVlc : Debug Buffering 63% @ main
libVlc : Debug Buffering 67% @ main
libVlc : Debug Buffering 71% @ main
libVlc : Debug Buffering 75% @ main
libVlc : Debug Buffering 79% @ main
libVlc : Debug Buffering 83% @ main
libVlc : Debug Buffering 87% @ main
libVlc : Debug Buffering 91% @ main
libVlc : Debug Buffering 95% @ main
libVlc : Debug Buffering 99% @ main
libVlc : Debug Stream buffering done (1030 ms in 897 ms) @ main
libVlc : Debug Decoder wait done in 0 ms @ main
libVlc : Debug tk->rtpSource->hasBeenSynchronizedUsingRTCP() @ live555
libVlc : Debug ES_OUT_RESET_PCR called @ main
libVlc : Debug Buffering 0% @ main
libVlc : Debug lost 144972 bytes @ live555
libVlc : Debug increasing buffer size to 1000000 @ live555
libVlc : Debug Buffering 28% @ main
libVlc : Debug Buffering 32% @ main
libVlc : Debug Buffering 36% @ main
libVlc : Debug Buffering 40% @ main
libVlc : Debug Buffering 44% @ main
libVlc : Debug Buffering 48% @ main
libVlc : Debug Buffering 52% @ main
libVlc : Debug Buffering 56% @ main
libVlc : Debug Buffering 60% @ main
libVlc : Debug Buffering 64% @ main
libVlc : Debug Buffering 68% @ main
libVlc : Debug Buffering 72% @ main
libVlc : Debug Buffering 76% @ main
libVlc : Debug Buffering 80% @ main
libVlc : Debug Buffering 84% @ main
libVlc : Debug Buffering 88% @ main
libVlc : Debug Buffering 92% @ main
libVlc : Debug Buffering 96% @ main
libVlc : Debug Buffering 100% @ main
libVlc : Debug Stream buffering done (1040 ms in 1062 ms) @ main
libVlc : Debug Decoder wait done in 0 ms @ main
libVlc : Debug killing decoder fourcc `h264' @ main
libVlc : Debug removing module "h264" @ main
libVlc : Debug removing a sout input (sout_input: 12C85F20) @ main
libVlc : Debug removing input @ mp4
libVlc : Debug Program doesn't contain anymore ES @ main
libVlc : Debug removing module "live555" @ main
libVlc : Debug tk 1 elst media time 0 duration 5070001 offset 0 @ mp4
libVlc : Debug tk 1 elst media time 5070001 duration 606945951 offset 0 @ mp4
libVlc : Warning no more input streams for this mux @ main
libVlc : Debug destroying input for 'rtsp://192.168.1.110:5504/channel=0,stream=0' @ main
```
