### ISSUE TITLE
System.ArgumentException: Media instance is not initialized.

### ISSUE THREAD

**Issue by bpcuong2013** [ZeBobo5/Vlc.DotNet#614]
I have an issue about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : 3.0.0
- **Vlc.DotNet project used** : WPF
- **libvlc version** : x64
- **.net version** : 4.6.2
- **Project language** : C#
- **Project build architecture** : x64
- **Operating system** : Windows x64

# Summary

I have 10 urls of media files, I call MediaPlayer.Play(new Uri(url)) continous in a short duration, and it causes the issue.

System.ArgumentException: Media instance is not initialized.
   at Vlc.DotNet.Core.Interops.VlcManager.GetMediaTracks(VlcMediaInstance mediaInstance)
   at Vlc.DotNet.Wpf.VlcVideoSourceProvider.VideoFormat(IntPtr& userdata, IntPtr chroma, UInt32& width, UInt32& height, UInt32& pitches, UInt32& lines)

- [Yes ] I confirm that my issue doesn't happen in VLC itself.

**Comment by jeremyVignelles** [comment]
Thanks for reporting,
Can you send me a minimal example project (for example a git repo on github) so that I can track down the issue?
This sounds like a race condition.

**Comment by chenxi5404** [comment]
This problem occurs when I set  images that are larger than 3M in size

**Comment by jeremyVignelles** [comment]
Can you send me a minimal repro?

**Comment by jeremyVignelles** [comment]
One workaround would be to call SetMedia, wait for the Parsed event, and then call Play(). We still need to fix this properly, but I need to reproduce this first to make sure that the fix is correct.

How can I do ? Can you send me a sample code where it does crash?

**Comment by olivegamestudio** [comment]
I'm getting this exception at startup. It definitely feels like a race condition because after a number of restarts of the app it works fine. I run through a sequence of videos and once up and running it can play the video on a subsequent pass. It's like the first video just causes it to fall over.
