### ISSUE TITLE
An unhandled exception of type 'System.AccessViolationException' occurred in Vlc.DotNet.Core.Interops.dll

### ISSUE THREAD

**Issue by spoiledtechie** [ZeBobo5/Vlc.DotNet#71]
getting an Access violation when trying to dispose of the player.  Under VLCPlayer on the Core library, VlcManager.ReleaseMediaPlayer.

An unhandled exception of type 'System.AccessViolationException' occurred in Vlc.DotNet.Core.Interops.dll

Additional information: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

   at Vlc.DotNet.Core.Interops.VlcManager.ReleaseMediaPlayer(VlcMediaPlayerInstance mediaPlayerInstance) in c:\Development\Vlc.DotNet\src\Vlc.DotNet.Core.Interops\VlcManager.ReleaseMediaPlayer.cs:line 14
   at Vlc.DotNet.Core.Interops.VlcMediaPlayerInstance.Dispose(Boolean disposing) in c:\Development\Vlc.DotNet\src\Vlc.DotNet.Core.Interops\VlcMediaPlayerInstance.cs:line 18
   at Vlc.DotNet.Core.Interops.Signatures.InteropObjectInstance.Dispose() in c:\Development\Vlc.DotNet\src\Vlc.DotNet.Core.Interops\Signatures\InteropObjectInstance.cs:line 21
   at Vlc.DotNet.Core.VlcMediaPlayer.Dispose(Boolean disposing) in c:\Development\Vlc.DotNet\src\Vlc.DotNet.Core\VlcMediaPlayer\VlcMediaPlayer.cs:line 105
   at Vlc.DotNet.Core.VlcMediaPlayer.Dispose() in c:\Development\Vlc.DotNet\src\Vlc.DotNet.Core\VlcMediaPlayer\VlcMediaPlayer.cs:line 87
   at Vlc.DotNet.Forms.VlcControl.Dispose(Boolean disposing) in c:\Development\Vlc.DotNet\src\Vlc.DotNet.Forms\VlcControl.cs:line 58
   at System.ComponentModel.Component.Dispose()
   at Vlc.DotNet.Wpf.Form.VlcControl.DestroyWindowCore(HandleRef hwnd) in c:\Development\Vlc.DotNet\src\Vlc.DotNet.Wpf\Form\VlcControl.cs:line 33
   at System.Windows.Interop.HwndHost.DestroyWindow()
   at System.Windows.Interop.HwndHost.Dispose(Boolean disposing)
   at System.Windows.Interop.HwndHost.Dispose()
   at TraqStudio.View.VideoEditingWindow.OnClosing(CancelEventArgs e) in c:\Development\TraQDigitalStudio\TraqStudio\View\VideoEditingWindow.xaml.cs:line 689
   at System.Windows.Window.WmClose()
   at System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

**Comment by hanzhangxian** [comment]
me too
please help us！！

**Comment by DominikPalo** [comment]
I have the same problem...

**Comment by marcomeyer** [comment]
It looks like it can be fixed by adding a ResetFromMedia() call when handling the Stopped event (similar to EndReached)

![image](https://cloud.githubusercontent.com/assets/1536469/8042799/e92b39aa-0e21-11e5-9dda-63330be47c24.png)
see also https://github.com/marcomeyer/Vlc.DotNet/commit/3fd4035ac2517e1bc42e4fdcf9201f96489436be

But since I am not familiar with the rest of the library, I don't know if this breaks with something else.

**Comment by AustinOberholtzer** [comment]
Getting this exact error, only some times. I have also tried a resolution to this by checking if VlcControl is disposed when checking if it is playing which seemed to work.

**Comment by SkinnySackboy** [comment]
Is anyone aware whether there is a strategic fix in the works for this?

**Comment by sepehr1014** [comment]
I was getting many error too, so I moved to https://github.com/higankanshi/xZune.Vlc

**Comment by SkinnySackboy** [comment]
Thanks sepehr1014, I'll give this a shot.

**Comment by sepehr1014** [comment]
Sure, it also doesn't have airspace issues in WPF and supports mouse/keyboard interaction (with DVD menus for example) and seems well maintained (although no documentation yet).

**Comment by higankanshi** [comment]
If many of people have used my project, I will add some documents and English comments for this.

**Comment by Victor-Hugo** [comment]
This is my VB.NET Solution for Vlc.DotNet.Forms


Dim VLC_Control As Vlc.DotNet.Forms.VlcControl
'------ VLC_Control instancing in other procedure
'------
'------
Sub EndWindowOrProgram()
            VLC_Control.Position = 31 '1f Hex
            Me.Controls.Remove(VLC_Control) 'Remove VLC control from current Form 
            GC.SuppressFinalize(VLC_Control) 'Force to dispose the object with garbage collector
            VLC_Control= Nothing
            End
End Sub
